name: Regression Tests

on:
  push:
    branches: [ master ]

jobs:
  web_tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install depencies
      run: npm install
    - name: Run Web Tests
      run: npm run headless
      continue-on-error: true
    
