name: Regression Tests

on:
  push:
    branches: [ master ]

jobs:
  web_tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - uses: actions/checkout@v2
    - name: Install depencies
      run: npm install
    - name: Run Web Tests
      run: npm run cy:run
      continue-on-error: true
    - name: Generate Report
      run: |
        npm run report:merge
        npm run report:mocha
   # Relatorio
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        BRANCH: gh_pages
        FOLDER: mochawesome-report
