name: Regression Tests

on:
  push:
    branches: [ master ]

jobs:
  web_tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install depencies
      run: npm install
    - name: Clean Report
      run: |
        npm run report:cleanup
        npm run video:cleanup
    - name: Run Web Tests
      run: npm run headless
      continue-on-error: true
    - run: npm run report:merge   
    - run: npm run report:generate
      # Relatorio
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        BRANCH: gh_pages
        FOLDER: ./output.html
